### ISSUE TITLE
Document that this tool is specifically for MySQL, or even TiDB?

### ISSUE THREAD

**Issue by breeswish** [pingcap/go-tpc#59]
This tool claims to be "A toolbox to benchmark TPC workloads in Go", but in fact it only supports MySQL protocol databases.

What's more, in PRs like https://github.com/pingcap/go-tpc/pull/58 TiDB specific hint syntax are introduced, which may not work for all MySQL protocol compatible databases.

For these reasons, I think we should at least claim this fact in README, or even rename the project (if supporting non TiDB database is not-a-goal), like "tidb-tpc", to avoid misleading others and waste their time.

**Comment by coocood** [comment]
that SQL with TIDB specific hint can run on MySQL.

**Comment by breeswish** [comment]
@coocood Thanks for the supplyment! I updated the description to "may not work for all MySQL protocol compatible databases" to be more accurate.

**Comment by at15** [comment]
Is it possible to add flags to disable/enable specific (type) of hint(s) so the benchmark suite becomes more general. It also add extra feature like comparing perf/result of using (different) hint(s).

btw: It would be easier to do this if the query are build from generator instead of written as string constant. Which would allow using the tool on postgres flavor SQL as well (e.g. `?` and `$1` etc.)
bbtw: Does TiDB has plan for supporting (basic) postgres syntax?

**Comment by breeswish** [comment]
@at15 Good idea, we may refering to [go-ycsb](https://github.com/pingcap/go-ycsb)'s approach to support multiple databases if it is an accepted feature. 

AFAIK there is no plan for TiDB to support PGSQL syntax.

**Comment by mahjonp** [comment]
> @coocood Thanks for the supplyment! I updated the description to "may not work for all MySQL protocol compatible databases" to be more accurate.

Thanks for your suggestion, we need to do our best to make sure that go-tpc works well for most MySQL compatible databases, but making it works for all MySQL compatible databases isn't realistic IMO.

So I plan to add a claim first and welcome any PR which can enhance the compatibility of go-tpc. :)

**Comment by breeswish** [comment]
Close for https://github.com/pingcap/go-tpc/pull/60
